name: farmer
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install wget
          pip install sklearn
          pip install pandas
          pip install seaborn
          pip install matplotlib
          dvc repro
          git fetch --prune
          dvc metrics diff --show-md master > report.md

          # Add figure to the report

          echo "## Validating results by region"

          cml-publish by_region.png --md >> report.md 
          cml-send-comment report.md
