name: farmer
on: [push]
jobs:
  build:
    #runs on Azure VM
    runs-on: self-hosted
    steps:            
    - name: "Login to Azure"
      uses: azure/CLI@v1
      with:
        azcliversion: 2.24.2
        inlineScript: |
          az login --identity
          az group list
          
